Add Shorthand for Install Command
srevinsaju/zap pull request #43
Opened 2021-10-05 17:51 UTC by hadihammurabi

use username/repository for github
use ./example.AppImage for local file with relative path
use /dir/example.AppImage for local file with absolute path

example:
![Zap Shorthand for Install Command](https://pasteboard.co/yBDDOnUJN2kE.png)

2021-10-05 17:55 UTC, srevinsaju requested changes

2021-10-05 17:55 UTC, srevinsaju commented on appimage.go
> +			panic(err)
But what about, when the provided command is?
```bash
zap install ./somedir/firefox.AppImage
```

2021-10-05 17:56 UTC, srevinsaju commented
Looks really neat! Thank you for your patch! :tada:

2021-10-05 18:20 UTC, hadihammurabi commented
I have fix thinks to change.
Please check

2021-10-05 20:34 UTC, srevinsaju commented on appimage.go
> +	context, appName := parseSourceFromAppName(context, context.Args().First())
Is it possible to calculate the `appName` from the parameter too, like
```bash
zap install repo/software1
```
should automatically set the `appName = software1`

and for local files
```bash
zap install ./super-cool-x86_64.AppImage
```
it should set `appName = super-cool`

2021-10-10 06:59 UTC, srevinsaju commented
@hadihammurabi are you still working on this, or shall I hand it over to @kadern0 ?

2021-10-10 08:44 UTC, hadihammurabi commented
Yes, i still collecting cpu architectures types.

2021-10-10 08:56 UTC, srevinsaju commented
@hadihammurabi it's there in the zap source code, https://github.com/srevinsaju/zap/blob/main/internal/helpers/arch.go, gives a list of supported architectures, but my proposed solution was more simpler than needing the list of architectures, but if it helps 🙂

2022-11-11 14:54 UTC, closed without merging